routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Login routes here
 * */
Route::get('login-election-portal','Auth\LoginController@showLoginForm')->name('login');
Route::post('login-election-portal','Auth\LoginController@login');
Route::post('logout','Auth\LoginController@logout')->name('logout');

//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Backend Routes
Route::middleware('auth')->namespace('Backend')->group(function () {
    // Admin Routes
    Route::middleware('auth')->namespace('Admin')->group(function () {

        Route::resource('admin', 'AdminController', ['only' => [
            'index', 'create', 'store', 'edit', 'update', 'show'
        ]]);
        Route::get('admin/delete/{id}', 'AdminController@destory')->name('admin.delete');
        Route::post('admin/status', 'AdminController@changeStatus')->name('admin.status');
    });
    //Api Manage Controller
    Route::middleware('auth')->namespace('Api')->group(function () {

        Route::get('api_manage', 'ApiManageController@editApi')->name('api_manage');
        Route::put('api_manage/update/{id}', 'ApiManageController@UpdateApi')->name('api_manage.update');
    });
    // Gallery Routes
    Route::middleware('auth')->namespace('Gallery')->group(function () {
        //Image Galley manage
        Route::resource('gallery_image', 'ImageGallery', ['only' => ['index','create', 'edit', 'update',]]);
        Route::post('image-gallery', 'ImageGallery@uploadImage')->name('image-gallery');
        Route::delete('image-gallery/{id}', 'ImageGallery@destroyImage');

        //Albums manage
        Route::get('list_albums', 'GalleryController@listAlbums')->name('list_albums');
        Route::post('list_albums/save', 'GalleryController@listAlbumsSave')->name('list_albums.save');
        Route::post('list_albums/update/{id}', 'GalleryController@listAlbumsUpdate')->name('list_albums.update');
        Route::delete('list_albums/delete/{id}', 'GalleryController@listAlbumsDelete');
        Route::post('posts/changeStatus', array('as' => 'changeStatus', 'uses' => 'GalleryController@changeStatus'));

        //Video Gallery manage
        Route::get('gallery_video', 'VideoGallery@videoIndex')->name('gallery_video');
        Route::get('gallery_video/create', 'VideoGallery@videoCreate')->name('gallery_video.create');
        Route::post('gallery_video/save', 'VideoGallery@videoSave')->name('gallery_video.save');
        Route::get('gallery_video/edit/{id}', 'VideoGallery@videoEdit')->name('gallery_video.edit');
        Route::put('gallery_video/update/{id}', 'VideoGallery@updateVideo')->name('gallery_video.update');
        Route::delete('gallery_video/delete/{id}', 'VideoGallery@videoDelete')->name('gallery_video.delete');;

    });
    //Opinion Manage
    Route::namespace('Opinion')->group(function () {
        Route::resource('opinion_manage','OpinionController');
        /*Route::resource('opinion_manage','OpinionController', ['only' => [
            'index', 'create', 'store', 'edit', 'update', 'show'
        ]]);
        Route::delete('opinion_manage/delete/{id}','OpinionController@deleteOpinion')->name('opinion_manage.delete');*/
    });

    // Live Video Manage
    Route::middleware('auth')->namespace('Live')->group(function () {

        Route::get('live_video','VideoController@getEdit')->name('live_video');
        Route::put('live_video/update/{id}','VideoController@UpdateLive')->name('live_video.update');

    });

    //Ads Manage
    Route::resource('ads_manage', 'AdsController', ['only' => [
        'index', 'edit', 'update'
    ]]);
//    Route::get('ads_manage/delete/{id}','AdsController@destroy')->name('ads_manage.delete');

    //ElectionManifesto Manage
    Route::resource('ishtehaar_manage', 'IshtehaarController', ['only' => [
        'index', 'create', 'store', 'edit', 'update', 'show'
    ]]);
    Route::delete('ishtehaar_manage/delete/{id}','IshtehaarController@destroy')->name('ishtehaar_manage.delete');

    //Seats Manage
    Route::get('seats_lists','SeatsController@getListofSeat')->name('seats_lists');
    Route::get('seats_lists/edit/{id}','SeatsController@editSeat')->name('seats_lists.edit');
    Route::put('seats_lists/update/{id}','SeatsController@updateSeat')->name('seats_lists.update');
	
	  //candidates Manage
     Route::namespace('Candidates')->group(function () {
        Route::resource('candidates_manage','CandidatesController');
		});
	
    //election_history Manage
    Route::namespace('ElectionHistories')->group(function () {
        Route::resource('election_history','ElectionHistoriesController');
		});
});
Route::post('district-ajax', 'Backend\SeatsController@districtAnyWhere')->name('district.check_ajax');
// Frontend Routes
Route::namespace('Frontend')->group(function () {
    Route::get('/','FrontendController@home')->name('election.home');
    Route::get('news-details/{id}','FrontendController@getDetails')->name('news.details');
    Route::get('video-gallery','FrontendController@getVideo')->name('video.gallery');
    Route::get('video-gallery/details/{id}','FrontendController@detailsVideoGallery')->name('video.details');
    Route::get('image-gallery','FrontendController@getImage')->name('image.gallery');
    Route::get('image-gallery/details/{id}','FrontendController@detailsImageGallery')->name('image.details');
    Route::get('election-manifesto','FrontendController@getIshtehaar')->name('election.manifesto');
    Route::get('seat/{id}/{title?}','FrontendController@getSeats')->name('seat');
	Route::get('election_history/{id}/{title?}','FrontendController@getElectionHistories')->name('election_history');

});

Route::get('/changePassword', 'HomeController@showChangePasswordForm')->name('changePassword');
Route::post('/changePassword', 'HomeController@changePassword')->name('changePassword');

app/Http/Controllers/Backend/Admin/AdminController.php
<?php

namespace App\Http\Controllers\Backend\Admin;


use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;
use Auth;
use Helper;

class AdminController extends Controller
{
    protected $alltypeuserlist;

    public function __construct(User $alltypeuserlist)
    {
        $this->alltypeuserlist = $alltypeuserlist;
        $this->middleware('auth');
    }

    public function index(Request $request)
    {

        $data['title'] = 'User lists';
        $all = $this->alltypeuserlist;


        if ($request->has('name') && $request->name != null) {
            $all = $all->where('name', 'like', '%' . $request->name . '%');
        }
        if ($request->has('email') && $request->email != null) {
            $all = $all->where('email', '=', $request->email);
        }
        $data['alltypeofuser'] = $all->where('email', '!=', auth()->user()->email)->paginate(config('system.pagination.items_per_page'));
        $data['serial'] = Helper::managePagination($data['alltypeofuser']);
        if ($request->ajax()) {
            return view('backend.users.table_load', $data)->render();
        }

        return view('backend.users.index', $data);
    }


    public function create()
    {
        $data['title'] = 'Create user';
        return view('backend.users.create', $data);
    }

    public function store(Request $request)
    {


        $request->validate([
            'name' => 'required|string',
            'email' => 'required|nullable|unique:users|email',
            'password' => 'required|confirmed'
        ]);

        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->save();

        Session::flash('message', 'User Successfully Created.');
        return redirect()->back();

    }

    public function show($id)
    {
        $data['showinfo'] = $this->alltypeuserlist->where('id', $id)->first();
        return view('backend.profile.profileInfo', $data);
    }

    public function edit($id)
    {
        $data['title'] = 'Edit user';
        $data['admin'] = User::findOrFail($id);
        return view('backend.users.edit', $data);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string',
            'email' => 'required|nullable|email|unique:users,email,'.$id,
        ]);

        $user = User::findOrFail($id);

        $user->name = $request->name;
        $user->email = $request->email;
        $user->save();
        Session::flash('message', 'User successfully updated.');
        return redirect()->back();
    }

    public function changeStatus(Request $req)
    {
        $status = User::find($req->id);
        $status->status = $req->status;
        $status->save();
        return response()->json(['status' => $status]);
    }


    public function destory($id)
    {
        $status = User::find($id);
        $status->delete();
        Session::flash('message', 'Successfully Deleted.');
        return redirect()->back();
    }


}

app/Http/Controllers/Backend/AdsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Ads;
use App\Helpers\Helper;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;

class AdsController extends Controller
{
    protected $alladslist;

    public function __construct(Ads $alladslist)
    {
        $this->alladslist = $alladslist;
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data['title']="Ads Lists";
        $all = $this->alladslist;

        if ($request->has('search') && $request->search != null) {
            $all = $all->where('page',$request->search);
        }

        $data['ads'] = $all->paginate(config('system.pagination.items_per_page'));
        $data['serial'] = Helper::managePagination($data['ads']);
        if ($request->ajax()) {
            return view('backend.ads.table_load', $data)->render();
        }
        return view('backend.ads.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['title']="Ads Create";
//        return view('backend.ads.create',$data);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'position_id' => 'required'
        ]);
        $checkAds=Ads::where('position_id',$request->position_id)->first();
        if (isset($checkAds)){
            Session::flash('warning', 'Ads Already Exist.');
            return Redirect::back()->withInput();
        }else{
            $input['position_id'] = $request->position_id;
            $input['position_name'] = AdsType::where('id',$request->position_id)->first()->type_name;
            $input['ads_code'] = $request->ads_code;
           // $input['image_path'] = $request->image_path;
           // $input['destination_path'] = $request->destination_path;
            $input['is_active'] = $request->is_active;
            Ads::create($input);
            Session::flash('message', 'Successfully Created.');
        }

        return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['title']="Edit Ads";
        $data['editAds']=Ads::where('id',$id)->first();
        return view('backend.ads.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'js_code_lg' => 'required',
            'js_code_md' => 'required',
            'js_code_xs' => 'required',
            'ads_code' => 'required',
            'status' => 'required'
        ]);

        $adsEdit = Ads::findOrFail($id);
        $adsEdit->js_code_lg = $request->js_code_lg;
        $adsEdit->js_code_md = $request->js_code_md;
        $adsEdit->js_code_xs = $request->js_code_xs;
        $adsEdit->ads_code = $request->ads_code;
        $adsEdit->status = $request->status;
        $adsEdit->save();

        Session::flash('message', 'Successfully Update.');
        return redirect()->route('ads_manage.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //

        $delAds=Ads::find($id);
        $delAds->delete();

        Session::flash('message', 'Successfully Deleted.');
        return redirect()->back();
    }
}

app/Http/Controllers/Backend/Api/ApiManageController.php
<?php

namespace App\Http\Controllers\Backend\Api;

use App\ApiManage;
use App\Helpers\Helper;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;

class ApiManageController extends Controller
{
    //


    public function editApi(){

        $data['title']="Update Api Data";
        $data['apiInfo']=ApiManage::latest('id')->first();
        $someArray = '{"Dogs":[{"category": "Companion dogs","name": "Chihuahua"}]}';
        if (empty($data['apiInfo'])) {
            ApiManage::insert(
                array(
                    'api_url'     =>   'Api Link here',
                    'api_data'   =>  json_decode($someArray)
                )
            );
        }
        return view('backend.api.edit',$data);
    }

    public function UpdateApi(Request $request,$id){
        $this->validate($request, [
            'api_url' => 'required',
            'api_data'=>'required',
        ]);

        if (isset($request->api_url)){
            $json=json_decode(Helper::request($request->api_url,null,$method=null),true);

        }else{
            $json=json_decode(Helper::request(config('system.api.home_news'),null,$method=null),true);

        }

        $apiData = ApiManage::findOrFail($id);
        $apiData->api_url = $request->api_url;
        $apiData->api_data = json_encode($json['items']);
        $apiData->save();

        Session::flash('message', 'Successfully Update.');
        return redirect()->back();
    }

    public function apiData(){

        $json = json_decode(Helper::request(config('system.api.home_news'),null, $method = null),true);
        $apiData = ApiManage::findOrFail(1);
        $apiData->api_url = config('system.api.home_news');
        $apiData->api_data = json_encode($json['items']);
        $apiData->save();
    }

}

app/Http/Controllers/Backend/Live/VideoController.php
<?php

namespace App\Http\Controllers\Backend\Live;

use App\LiveVideo;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;

class VideoController extends Controller
{
    //
    public function getEdit(){
        $data['title']="Update Live Link";
        $data['liveLink']=LiveVideo::latest('id')->first();

        if (empty($data['liveLink'])) {

            LiveVideo::insert(array('live_link'     =>   'Live Video Link Enter here'));
        }
        return view('backend.live.video.edit',$data);
    }

    public function UpdateLive(Request $request,$id){

        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'live_link' => 'required',
            'status'=>'required'
        ]);
        $upLive = LiveVideo::findOrFail($id);
        $upLive->title=$request->title;
        $upLive->description=$request->description;
        $upLive->live_link=$request->live_link;
        $upLive->status=$request->status;
        $upLive->save();
        Session::flash('message', 'Successfully Update.');
        return redirect()->back();
    }
}

resources/views/layouts/backend/_footer.blade.php
<div class="text-center">
   <?php echo date('Y'); ?> &copy;  ADN Digital.
    <a href="#" class="go-top">
        <i class="fa fa-angle-up"></i>
    </a>
</div>

resources/views/layouts/backend/_head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="Mosaddek">
<meta name="keyword" content="ADN Digital">
<link rel="shortcut icon" href="{{ asset('img/adn_favicon.png') }}">
<meta name="csrf-token" content="{{ csrf_token() }}">

<title>{{ isset($title)?$title:'bdnews24 election portal' }}</title>

<!-- Bootstrap core CSS -->
<link href="{!! asset('css/bootstrap.min.css') !!}" rel="stylesheet">
<link href="{!! asset('css/bootstrap-reset.css') !!}" rel="stylesheet">
<!--external css-->
<link href="{!! asset('assets/font-awesome/css/font-awesome.css') !!}" rel="stylesheet" />
<link href="{!! asset('assets/toastr-master/toastr.css') !!}" rel="stylesheet" type="text/css" />


<!-- Custom styles for this template -->

<link href="{!! asset('css/style.css') !!}" rel="stylesheet">
<link href="{!! asset('css/style-responsive.css') !!}" rel="stylesheet" />
<link href="{!! asset('css/custom.css') !!}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{!! asset('assets/bootstrap-datepicker/css/datepicker.css') !!}" />
@stack('css')
<style>
    /*footer fixed design*/
    .site-footer {
        position: fixed;
        width: 100%;
        bottom: 0px;
    }
    .adv-table .dataTables_filter label input{
        margin-top: -35px;
        -webkit-appearance: button!important;
    }
    .dataTables_wrapper .dataTables_filter{
        text-align: left;
    }
    .adv-table .dataTables_length select{
        padding: 1px 0px !important;
    }
</style>
<!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
<!--[if lt IE 9]>
<script src="{!! asset('js/html5shiv.js') !!}"></script>
<script src="{!! asset('js/respond.min.js') !!}"></script>
<![endif]-->
<!-- Imoportant JS -->
<script src="{!! asset('js/jquery.js') !!}"></script>
<script src="{!! asset('js/bootstrap.min.js') !!}"></script>
<!-- Imoportant JS -->
<script type="text/javascript" src="{!! asset('assets/bootstrap-datepicker/js/bootstrap-datepicker.js') !!}"></script>

resources/views/layouts/backend/_header.blade.php
<div class="sidebar-toggle-box">
    <i class="fa fa-bars"></i>
</div>
<!--logo start-->
<a href="{!! route('home') !!}" class="logo"> Election <span>Portal</span></a>
<!--logo end-->
<div class="nav notify-row" id="top_menu">
    <!--  notification start -->
    <ul class="nav top-menu">
        <!-- settings start -->

        <!-- notification dropdown end -->
    </ul>
    <!--  notification end -->
</div>
<div class="top-nav ">
    <!--search & user info start-->
    <ul class="nav pull-right top-menu">
        <li>
            {{--<input type="text" class="form-control search" placeholder="Search">--}}
        </li>
        <!-- user login dropdown start-->
        <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                {{--<img alt="" src="{!! asset('img/avatar1_small.jpg') !!}">--}}
                <span class="username"><i class="fa fa-user"></i> {{Auth::user()->name}}</span>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu extended logout">
                <div class="log-arrow-up"></div>
                <li><a href="#"><i class=" fa fa-suitcase"></i>Profile</a></li>
                <li><a href="#"><i class="fa fa-cog"></i> Settings</a></li>
                <li><a href="{{route("changePassword")}}"><i class="fa fa-key"></i> Change <br>Password</a></li>
                <li>
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        <i class="fa fa-sign-out"></i> {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </li>
            </ul>
        </li>
        <li class="sb-toggle-right">
            {{--<i class="fa  fa-align-right"></i>--}}
        </li>
        <!-- user login dropdown end -->
    </ul>
    <!--search & user info end-->
</div>

resources/views/layouts/backend/_messages.blade.php
<message>
        {{--set some message after action--}}

        @if (\Session::has('message'))
                <script>
                    toastr.success('{!! \Session::get("message") !!}');
                </script>
        @elseif(\Session::has('warning'))
                <script>
                    toastr.warning('{!! \Session::get("warning") !!}');
                </script>
        @elseif(\Session::has('info'))
                <script>
                    toastr.info('{!! \Session::get("info") !!}');
                </script>
        @elseif(\Session::has('danger'))
                <script>
                    toastr.error('{!! \Session::get("danger") !!}');
                </script>
        @endif
</message>

resources/views/layouts/backend/_nav.blade.php
<div id="sidebar" class="nav-collapse ">
    <!-- sidebar menu start-->
    <ul class="sidebar-menu" id="nav-accordion">
        <li>
            <a class="{{ request()->segment(1) == 'home' ? 'active' : null }}" href="{!! route('home') !!}">
                <i class="fa fa-dashboard"></i>
                <span>Dashboard</span>
            </a>
        </li>
        <li>
            <a class="{{ request()->segment(1) == 'api_manage' ? 'active' : null }}" href="{!! route('api_manage') !!}">
                <i class="fa fa-asterisk"></i>
                <span>Api Manage</span>
            </a>
        </li>
        <li>
            <a class="{{ request()->segment(1) == 'seats_lists' ? 'active' : null }}"
               href="{!! route('seats_lists') !!}">
                <i class="fa fa-plus-square-o"></i>
                <span>Seats  Lists</span>
            </a>
        </li>
	
		
		 <li class="sub-menu">
            <a href="javascript:;" class="{{ request()->segment(1) == 'election_history' ? 'active' : null }}">
                <i class="fa fa-gavel"></i>
                <span>Election History</span>
            </a>
            <ul class="sub">

                <li class="{{ request()->segment(2) == 'create' ? 'active' : null }}"><a
                            href="{{ route('election_history.create') }}"> Create</a></li>
                <li class="{{ request()->segment(2) == 'list' ? 'active' : null }}"><a
                            href="{{ route('election_history.index') }}">Lists</a></li>

            </ul>
        </li>

		 <li class="sub-menu">
            <a href="javascript:;" class="{{ request()->segment(1) == 'candidates_manage' ? 'active' : null }}">
                <i class="fa fa-gavel"></i>
                <span>Candidates</span>
            </a>
            <ul class="sub">

                <li class="{{ request()->segment(2) == 'create' ? 'active' : null }}"><a
                            href="{{ route('candidates_manage.create') }}"> Create</a></li>
                <li class="{{ request()->segment(2) == 'list' ? 'active' : null }}"><a
                            href="{{ route('candidates_manage.index') }}">Lists</a></li>

            </ul>
        </li>

		
		
		
        <li class="sub-menu">
            <a href="javascript:;" class="{{ request()->segment(1) == 'opinion_manage' ? 'active' : null }}">
                <i class="fa fa-gavel"></i>
                <span>Opinion</span>
            </a>
            <ul class="sub">

                <li class="{{ request()->segment(2) == 'create' ? 'active' : null }}"><a
                            href="{{ route('opinion_manage.create') }}"> Create</a></li>
                <li class="{{ request()->segment(2) == 'index' ? 'active' : null }}"><a
                            href="{{ route('opinion_manage.index') }}">Lists</a></li>

            </ul>
        </li>


        {{--    <li class="sub-menu">
                <a href="javascript:;" class="{{ request()->segment(1) == 'ads_manage' ? 'active' : null }}" >
                    <i class="fa fa-gavel"></i>
                    <span>Ads </span>
                </a>
                <ul class="sub">

                    <li class="{{ request()->segment(2) == 'index' ? 'active' : null }}"><a href="{{ route('ads_manage.create') }}"> Create</a></li>
                    <li class="{{ request()->segment(2) == 'create' ? 'active' : null }}"><a href="{{ route('ads_manage.index') }}">Lists</a></li>

                </ul>
            </li>--}}

        <li class="sub-menu">
            <a href="javascript:;" class="{{ request()->segment(1) == 'ishtehaar_manage' ? 'active' : null }}">
                <i class="fa fa-gavel"></i>
                <span>Ishtehaar </span>
            </a>
            <ul class="sub">

                <li class="{{ request()->segment(2) == 'create' ? 'active' : null }}"><a
                            href="{{ route('ishtehaar_manage.create') }}"> Create</a></li>
                <li class="{{ request()->segment(2) == 'index' ? 'active' : null }}"><a
                            href="{{ route('ishtehaar_manage.index') }}">Lists</a></li>

            </ul>
        </li>
        <li>
            <a class="{{ request()->segment(1) == 'list_albums' ? 'active' : null }}"
               href="{!! route('list_albums') !!}">
                <i class="fa   fa-book"></i>
                <span>Manage Albums</span>
            </a>
        </li>

        <li class="sub-menu">
            <a href="javascript:;" class="{{ request()->segment(1) == 'gallery_video' ? 'active' : null }}">
                <i class="fa fa-video-camera"></i>
                <span>Video Gallery</span>
            </a>
            <ul class="sub">

                <li class="{{ request()->segment(2) == 'create' ? 'active' : null }}"><a
                            href="{{ route('gallery_video.create') }}">Create Video</a></li>
                <li class="{{ request()->segment(2) == 'gallery_video' ? 'active' : null }}"><a
                            href="{{ route('gallery_video') }}">List Video</a></li>

            </ul>
        </li>
        <li class="sub-menu">
            <a href="javascript:;" class="{{ request()->segment(1) == 'gallery_image' ? 'active' : null }}">
                <i class="fa fa-picture-o"></i>
                <span>Image Gallery</span>
            </a>
            <ul class="sub">
                <li class="{{ request()->segment(2) == 'create' ? 'active' : null }}"><a
                            href="{{ route('gallery_image.create') }}"> Create</a></li>

                <li class="{{ request()->segment(2) == 'index' ? 'active' : null }}"><a
                            href="{{ route('gallery_image.index') }}"> Lists</a></li>

            </ul>
        </li>

        <li>
            <a class="{{ request()->segment(1) == 'live_video' ? 'active' : null }}" href="{!! route('live_video') !!}">
                <i class="fa fa-circle" style="color:#FF5757"></i>
                <span>Live Video</span>
            </a>
        </li>
        <li>
            <a class="{{ request()->segment(1) == 'ads_manage' ? 'active' : null }}"
               href="{{ route('ads_manage.index') }}">
                <i class="fa fa-plus-square-o"></i>
                <span>Ads</span>
            </a>
        </li>
        <li class="sub-menu">
            <a href="javascript:;" class="{{ request()->segment(1) == 'admin' ? 'active' : null }}">
                <i class="fa fa-user"></i>
                <span>Users</span>
            </a>
            <ul class="sub">
                <li class="{{ request()->segment(2) == 'create' ? 'active' : null }}"><a
                            href="{{ route('admin.create') }}"> Create</a></li>

                <li class="{{ request()->segment(2) == 'index' ? 'active' : null }}"><a
                            href="{{ route('admin.index') }}"> List</a></li>
            </ul>
        </li>

    </ul>
    <!-- sidebar menu end-->
</div>

resources/views/layouts/backend/_scripts.blade.php
<script type="text/javascript" src="{!! asset('assets/ckeditor/ckeditor.js') !!}"></script>

<!-- js placed at the end of the document so the pages load faster -->
<script class="include" type="text/javascript" src="{!! asset('js/jquery.dcjqaccordion.2.7.js') !!}"></script>
<script src="{!! asset('js/jquery.scrollTo.min.js') !!}"></script>

<script src="{!! asset('assets/toastr-master/toastr.js') !!}"></script>
<!--toastr js-->
@include('layouts.backend._messages')

<!--common script for all pages-->
<script src="{!! asset('js/common-scripts.js') !!}"></script>
<script src="{{ asset('js/custom.js') }}"></script>
<script>

    var ajaxurl='{!!route('district.check_ajax')!!}';
    function districtControl(action,id){
        var query={'action':action,'id':id,"_token": "{{ csrf_token() }}"};
        $.ajax({
            url:ajaxurl,
            data:query,
            type: "post",
            cache: false
        }).success(function(data){
            switch(action){
                case 'district':
                    $("#district").html(data);
                break;
            }
        });
    }

</script>

@stack('js')

resources/views/layouts/backend/_validationErrorMessages.blade.php
@if($errors->any())
    <ul class="alert alert-danger fade in animated slideInRight alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close"><i  class="fa fa-times" aria-hidden="true"></i></a>
        @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
@endif

{{--

@if (count($errors) > 0)
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif--}}