routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Login routes here
 * */
Route::get('login-election-portal','Auth\LoginController@showLoginForm')->name('login');
Route::post('login-election-portal','Auth\LoginController@login');
Route::post('logout','Auth\LoginController@logout')->name('logout');

//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Backend Routes
Route::middleware('auth')->namespace('Backend')->group(function () {
    // Admin Routes
    Route::middleware('auth')->namespace('Admin')->group(function () {

        Route::resource('admin', 'AdminController', ['only' => [
            'index', 'create', 'store', 'edit', 'update', 'show'
        ]]);
        Route::get('admin/delete/{id}', 'AdminController@destory')->name('admin.delete');
        Route::post('admin/status', 'AdminController@changeStatus')->name('admin.status');
    });
    //Api Manage Controller
    Route::middleware('auth')->namespace('Api')->group(function () {

        Route::get('api_manage', 'ApiManageController@editApi')->name('api_manage');
        Route::put('api_manage/update/{id}', 'ApiManageController@UpdateApi')->name('api_manage.update');
    });
    // Gallery Routes
    Route::middleware('auth')->namespace('Gallery')->group(function () {
        //Image Galley manage
        Route::resource('gallery_image', 'ImageGallery', ['only' => ['index','create', 'edit', 'update',]]);
        Route::post('image-gallery', 'ImageGallery@uploadImage')->name('image-gallery');
        Route::delete('image-gallery/{id}', 'ImageGallery@destroyImage');

        //Albums manage
        Route::get('list_albums', 'GalleryController@listAlbums')->name('list_albums');
        Route::post('list_albums/save', 'GalleryController@listAlbumsSave')->name('list_albums.save');
        Route::post('list_albums/update/{id}', 'GalleryController@listAlbumsUpdate')->name('list_albums.update');
        Route::delete('list_albums/delete/{id}', 'GalleryController@listAlbumsDelete');
        Route::post('posts/changeStatus', array('as' => 'changeStatus', 'uses' => 'GalleryController@changeStatus'));

        //Video Gallery manage
        Route::get('gallery_video', 'VideoGallery@videoIndex')->name('gallery_video');
        Route::get('gallery_video/create', 'VideoGallery@videoCreate')->name('gallery_video.create');
        Route::post('gallery_video/save', 'VideoGallery@videoSave')->name('gallery_video.save');
        Route::get('gallery_video/edit/{id}', 'VideoGallery@videoEdit')->name('gallery_video.edit');
        Route::put('gallery_video/update/{id}', 'VideoGallery@updateVideo')->name('gallery_video.update');
        Route::delete('gallery_video/delete/{id}', 'VideoGallery@videoDelete')->name('gallery_video.delete');;

    });
    //Opinion Manage
    Route::namespace('Opinion')->group(function () {
        Route::resource('opinion_manage','OpinionController');
        /*Route::resource('opinion_manage','OpinionController', ['only' => [
            'index', 'create', 'store', 'edit', 'update', 'show'
        ]]);
        Route::delete('opinion_manage/delete/{id}','OpinionController@deleteOpinion')->name('opinion_manage.delete');*/
    });

    // Live Video Manage
    Route::middleware('auth')->namespace('Live')->group(function () {

        Route::get('live_video','VideoController@getEdit')->name('live_video');
        Route::put('live_video/update/{id}','VideoController@UpdateLive')->name('live_video.update');

    });

    //Ads Manage
    Route::resource('ads_manage', 'AdsController', ['only' => [
        'index', 'edit', 'update'
    ]]);
//    Route::get('ads_manage/delete/{id}','AdsController@destroy')->name('ads_manage.delete');

    //ElectionManifesto Manage
    Route::resource('ishtehaar_manage', 'IshtehaarController', ['only' => [
        'index', 'create', 'store', 'edit', 'update', 'show'
    ]]);
    Route::delete('ishtehaar_manage/delete/{id}','IshtehaarController@destroy')->name('ishtehaar_manage.delete');

    //Seats Manage
    Route::get('seats_lists','SeatsController@getListofSeat')->name('seats_lists');
    Route::get('seats_lists/edit/{id}','SeatsController@editSeat')->name('seats_lists.edit');
    Route::put('seats_lists/update/{id}','SeatsController@updateSeat')->name('seats_lists.update');
	
	  //candidates Manage
     Route::namespace('Candidates')->group(function () {
        Route::resource('candidates_manage','CandidatesController');
		});
	
    //election_history Manage
    Route::namespace('ElectionHistories')->group(function () {
        Route::resource('election_history','ElectionHistoriesController');
		});
});
Route::post('district-ajax', 'Backend\SeatsController@districtAnyWhere')->name('district.check_ajax');
// Frontend Routes
Route::namespace('Frontend')->group(function () {
    Route::get('/','FrontendController@home')->name('election.home');
    Route::get('news-details/{id}','FrontendController@getDetails')->name('news.details');
    Route::get('video-gallery','FrontendController@getVideo')->name('video.gallery');
    Route::get('video-gallery/details/{id}','FrontendController@detailsVideoGallery')->name('video.details');
    Route::get('image-gallery','FrontendController@getImage')->name('image.gallery');
    Route::get('image-gallery/details/{id}','FrontendController@detailsImageGallery')->name('image.details');
    Route::get('election-manifesto','FrontendController@getIshtehaar')->name('election.manifesto');
    Route::get('seat/{id}/{title?}','FrontendController@getSeats')->name('seat');
	Route::get('election_history/{id}/{title?}','FrontendController@getElectionHistories')->name('election_history');

});

Route::get('/changePassword', 'HomeController@showChangePasswordForm')->name('changePassword');
Route::post('/changePassword', 'HomeController@changePassword')->name('changePassword');

app/Opinion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Opinion extends Model
{
    protected $table = 'opinions';
    protected $fillable=['title','image_url','sequence','short_details','opinion_details_link','status'];
}

app/Http/Controllers/Backend/Admin/AdminController.php
<?php

namespace App\Http\Controllers\Backend\Admin;


use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;
use Auth;
use Helper;

class AdminController extends Controller
{
    protected $alltypeuserlist;

    public function __construct(User $alltypeuserlist)
    {
        $this->alltypeuserlist = $alltypeuserlist;
        $this->middleware('auth');
    }

    public function index(Request $request)
    {

        $data['title'] = 'User lists';
        $all = $this->alltypeuserlist;


        if ($request->has('name') && $request->name != null) {
            $all = $all->where('name', 'like', '%' . $request->name . '%');
        }
        if ($request->has('email') && $request->email != null) {
            $all = $all->where('email', '=', $request->email);
        }
        $data['alltypeofuser'] = $all->where('email', '!=', auth()->user()->email)->paginate(config('system.pagination.items_per_page'));
        $data['serial'] = Helper::managePagination($data['alltypeofuser']);
        if ($request->ajax()) {
            return view('backend.users.table_load', $data)->render();
        }

        return view('backend.users.index', $data);
    }


    public function create()
    {
        $data['title'] = 'Create user';
        return view('backend.users.create', $data);
    }

    public function store(Request $request)
    {


        $request->validate([
            'name' => 'required|string',
            'email' => 'required|nullable|unique:users|email',
            'password' => 'required|confirmed'
        ]);

        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->save();

        Session::flash('message', 'User Successfully Created.');
        return redirect()->back();

    }

    public function show($id)
    {
        $data['showinfo'] = $this->alltypeuserlist->where('id', $id)->first();
        return view('backend.profile.profileInfo', $data);
    }

    public function edit($id)
    {
        $data['title'] = 'Edit user';
        $data['admin'] = User::findOrFail($id);
        return view('backend.users.edit', $data);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string',
            'email' => 'required|nullable|email|unique:users,email,'.$id,
        ]);

        $user = User::findOrFail($id);

        $user->name = $request->name;
        $user->email = $request->email;
        $user->save();
        Session::flash('message', 'User successfully updated.');
        return redirect()->back();
    }

    public function changeStatus(Request $req)
    {
        $status = User::find($req->id);
        $status->status = $req->status;
        $status->save();
        return response()->json(['status' => $status]);
    }


    public function destory($id)
    {
        $status = User::find($id);
        $status->delete();
        Session::flash('message', 'Successfully Deleted.');
        return redirect()->back();
    }


}

app/Http/Controllers/Backend/AdsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Ads;
use App\Helpers\Helper;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;

class AdsController extends Controller
{
    protected $alladslist;

    public function __construct(Ads $alladslist)
    {
        $this->alladslist = $alladslist;
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data['title']="Ads Lists";
        $all = $this->alladslist;

        if ($request->has('search') && $request->search != null) {
            $all = $all->where('page',$request->search);
        }

        $data['ads'] = $all->paginate(config('system.pagination.items_per_page'));
        $data['serial'] = Helper::managePagination($data['ads']);
        if ($request->ajax()) {
            return view('backend.ads.table_load', $data)->render();
        }
        return view('backend.ads.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['title']="Ads Create";
//        return view('backend.ads.create',$data);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'position_id' => 'required'
        ]);
        $checkAds=Ads::where('position_id',$request->position_id)->first();
        if (isset($checkAds)){
            Session::flash('warning', 'Ads Already Exist.');
            return Redirect::back()->withInput();
        }else{
            $input['position_id'] = $request->position_id;
            $input['position_name'] = AdsType::where('id',$request->position_id)->first()->type_name;
            $input['ads_code'] = $request->ads_code;
           // $input['image_path'] = $request->image_path;
           // $input['destination_path'] = $request->destination_path;
            $input['is_active'] = $request->is_active;
            Ads::create($input);
            Session::flash('message', 'Successfully Created.');
        }

        return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['title']="Edit Ads";
        $data['editAds']=Ads::where('id',$id)->first();
        return view('backend.ads.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'js_code_lg' => 'required',
            'js_code_md' => 'required',
            'js_code_xs' => 'required',
            'ads_code' => 'required',
            'status' => 'required'
        ]);

        $adsEdit = Ads::findOrFail($id);
        $adsEdit->js_code_lg = $request->js_code_lg;
        $adsEdit->js_code_md = $request->js_code_md;
        $adsEdit->js_code_xs = $request->js_code_xs;
        $adsEdit->ads_code = $request->ads_code;
        $adsEdit->status = $request->status;
        $adsEdit->save();

        Session::flash('message', 'Successfully Update.');
        return redirect()->route('ads_manage.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //

        $delAds=Ads::find($id);
        $delAds->delete();

        Session::flash('message', 'Successfully Deleted.');
        return redirect()->back();
    }
}

app/Http/Controllers/Backend/Api/ApiManageController.php
<?php

namespace App\Http\Controllers\Backend\Api;

use App\ApiManage;
use App\Helpers\Helper;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;

class ApiManageController extends Controller
{
    //


    public function editApi(){

        $data['title']="Update Api Data";
        $data['apiInfo']=ApiManage::latest('id')->first();
        $someArray = '{"Dogs":[{"category": "Companion dogs","name": "Chihuahua"}]}';
        if (empty($data['apiInfo'])) {
            ApiManage::insert(
                array(
                    'api_url'     =>   'Api Link here',
                    'api_data'   =>  json_decode($someArray)
                )
            );
        }
        return view('backend.api.edit',$data);
    }

    public function UpdateApi(Request $request,$id){
        $this->validate($request, [
            'api_url' => 'required',
            'api_data'=>'required',
        ]);

        if (isset($request->api_url)){
            $json=json_decode(Helper::request($request->api_url,null,$method=null),true);

        }else{
            $json=json_decode(Helper::request(config('system.api.home_news'),null,$method=null),true);

        }

        $apiData = ApiManage::findOrFail($id);
        $apiData->api_url = $request->api_url;
        $apiData->api_data = json_encode($json['items']);
        $apiData->save();

        Session::flash('message', 'Successfully Update.');
        return redirect()->back();
    }

    public function apiData(){

        $json = json_decode(Helper::request(config('system.api.home_news'),null, $method = null),true);
        $apiData = ApiManage::findOrFail(1);
        $apiData->api_url = config('system.api.home_news');
        $apiData->api_data = json_encode($json['items']);
        $apiData->save();
    }

}

app/Http/Controllers/Backend/Live/VideoController.php
<?php

namespace App\Http\Controllers\Backend\Live;

use App\LiveVideo;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;

class VideoController extends Controller
{
    //
    public function getEdit(){
        $data['title']="Update Live Link";
        $data['liveLink']=LiveVideo::latest('id')->first();

        if (empty($data['liveLink'])) {

            LiveVideo::insert(array('live_link'     =>   'Live Video Link Enter here'));
        }
        return view('backend.live.video.edit',$data);
    }

    public function UpdateLive(Request $request,$id){

        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'live_link' => 'required',
            'status'=>'required'
        ]);
        $upLive = LiveVideo::findOrFail($id);
        $upLive->title=$request->title;
        $upLive->description=$request->description;
        $upLive->live_link=$request->live_link;
        $upLive->status=$request->status;
        $upLive->save();
        Session::flash('message', 'Successfully Update.');
        return redirect()->back();
    }
}

resources/views/backend/opinion/_form.blade.php
<div class="form-group">
    {!! Html::decode(Form::label('title','Title <sup> <span class="red">*</span></sup>',['class'=>'col-lg-2 col-sm-2 control-label text-right']))!!}
    <div class="col-lg-8">
        <div class="iconic-input right">
            {!! Form::text('title',null,['class'=>'form-control','required','placeholder'=>'Write title here','required']) !!}
        </div>
    </div>
</div>
<div class="form-group">
    {!! Html::decode(  Form::label('path','Image Url <sup> <span class="red">*</span></sup>',['class'=>'col-lg-2 col-sm-2 control-label']) )!!}
    <div class="col-md-8">
        <div class="iconic-input right">
            {!! Form::textarea('image_url',null,['cols'=>5,'rows'=>2,'class'=>'form-control','required','placeholder'=>'Write image url here','required']) !!}
        </div>
    </div>
</div>
<div class="form-group">
    {!! Html::decode(  Form::label('opinion_details_link','Destination Path <sup> <span class="red">*</span></sup>',['class'=>'col-lg-2 col-sm-2 control-label']) )!!}
    <div class="col-md-8">
        <div class="iconic-input right">
            {!! Form::textarea('opinion_details_link',null,['cols'=>5,'rows'=>2,'class'=>'form-control','required','placeholder'=>'Write destination url here']) !!}
        </div>
    </div>
</div>
<div class="form-group">
    {!! Html::decode(  Form::label('sequence','Sequence  ',['class'=>'col-lg-2 col-sm-2 control-label']) )!!}
    <div class="col-lg-8">
        <div class="iconic-input right">
            {!! Form::number('sequence',null,['class'=>'form-control','placeholder'=>'Select Sequence','min'=>0]) !!}
        </div>
    </div>
</div>
<div class="form-group">
    {!! Html::decode(  Form::label('opinion_details_link','Short Description <sup> <span class="red">*</span></sup>',['class'=>'col-lg-2 col-sm-2 control-label']) )!!}
    <div class="col-md-8">
        <div class="iconic-input right">
            {!! Form::textarea('short_details',null,['cols'=>5,'rows'=>5,'class'=>'form-control' ]) !!}

        </div>
    </div>
</div>
<div class="form-group">
    {!! Html::decode(  Form::label('is_active','Status <sup> <span class="red">*</span></sup>',['class'=>'col-lg-2 col-sm-2 control-label']) )!!}
    <div class="col-lg-8">

        <div class="iconic-input right" style="display: inline-flex;">

            <div class="radio">
                <label>
                    {!! Form::radio('status','Unpublished',['class'=>'form-control','required','id'=>'optionsRadios2'])!!}
                    Unpublished
                </label>
            </div>
            <div class="radio">
                <label>
                    {!! Form::radio('status','Published',['class'=>'form-control','required','id'=>'optionsRadios1','checked'])!!}
                    Published
                </label>
            </div>
        </div>

    </div>
</div>

resources/views/backend/opinion/_script.blade.php
<script>
    // for ajax pagination without load
    $(function() {
        $('body').on('click', '.pagination a', function(e) {
            e.preventDefault();

            $('#load a').css('color', '#dfecf6');
            $('#load').append('<img style="position: absolute; left: 0; top: 0; z-index: 100000;" src="/img/loading2.gif" />');

            var url = $(this).attr('href');
            getArticles(url);
            window.history.pushState("", "", url);
        });

        function getArticles(url) {
            $.ajax({
                url : url
            }).done(function (data) {
                $('.userlistofadmin').html(data);
            }).fail(function () {
                alert('Data could not be loaded.');
            });
        }


    });
    // delete a post
    $(document).on('click', '.delete-modal', function () {
        $('.modal-title').text('Delete');
        $('#id_delete').val($(this).data('id'));
        $('#title_delete').val($(this).data('title'));
        $('#title').html($(this).data('title'));

        $('#deleteModal').modal('show');
        id = $('#id_delete').val();
    });
    $('.modal-footer').on('click', '.delete', function () {
        $.ajax({
            type: 'DELETE',
            url: '{{url("opinion_manage")}}/' + id,
            data: {
                '_token': $('input[name=_token]').val(),
            },
            success: function (data) {
                toastr.success('Successfully deleted Post!', 'Success Alert', {timeOut: 5000});
                $('.item' + data['id']).remove();
            }
        });
    });
</script>

resources/views/backend/opinion/create.blade.php
@extends('layouts.backend.master')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <header class="panel-heading">
                    Create Opinion
                </header>
                <div class="panel-body">
                    @include('layouts.backend._validationErrorMessages')
                    {!! Form::open(['route'=>'opinion_manage.store','class'=>'form-horizontal','enctype'=>"multipart/form-data",'id'=>'userform']) !!}
                    <div class="col-md-8 col-md-offset-2">
                        @include("backend.opinion._form")
                        <div class="form-group">

                            <div class="col-md-8 col-md-offset-2">
                                <a href="{{ route('opinion_manage.index') }}" class="btn btn-warning pull-right" onclick="return confirm('Are you confirm ?')"> <i class="fa fa-arrow-left"></i> Back</a>
                                {!! Form::submit('Save',['class'=>'btn btn-success btnCreate pull-left']) !!}
                            </div>

                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection
@push('css')

@endpush
@push('js')
    <!--this page  script only-->
    <script src="{{ asset('js/advanced-form-components.js') }}"></script>

    @include('backend.opinion._script')
@endpush

resources/views/backend/opinion/edit.blade.php
@extends('layouts.backend.master')
@section('content')
<div class="row">
    <div class="col-md-12">
        <section class="panel">
            <header class="panel-heading">
                Update Opinion
            </header>
            <div class="panel-body">
                @include('layouts.backend._validationErrorMessages')
                {!! Form::model($opinionEdit,['route'=>['opinion_manage.update',$opinionEdit->id],'method'=>'put','class'=>'form-horizontal','enctype'=>"multipart/form-data",'id'=>'userform']) !!}
                <div class="col-md-8 col-md-offset-2">
                @include('backend.opinion._form')
                    <div class="form-group">
                        <div class="col-md-8 col-md-offset-2">
                            {!! Form::submit('Update',['class'=>'btn btn-success btnCreate pull-left']) !!}
                            <a href="{{ route('opinion_manage.index') }}" class="btn btn-warning pull-right" onclick="return confirm('Are you confirm ?')"> <i class="fa fa-arrow-left"></i> Back</a>
                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </section>
    </div>
</div>
@endsection
@push('css')
@endpush
@push('js')
    <!--this page  script only-->
    <script src="{{ asset('js/advanced-form-components.js') }}"></script>
    @include('backend.opinion._script')
@endpush

resources/views/backend/opinion/index.blade.php
@extends('layouts.backend.master')
@section('content')
     <div class="row">
         <div class="col-sm-12">
             <section class="panel">
                 <header class="panel-heading">
                     Opinion Lists
                 </header>
                 <div class="panel-body">
                     <div class="content">
                         <div class="row">
                             <div class="col-md-1">
                           <a href="{{route('opinion_manage.create')}}" class="btn btn-success pull-left m-5"><i   class="fa fa-plus"></i> Create</a>
                             </div>

                             {{ Form::open(['method'=>'get']) }}
                             <div class="col-md-3 col-md-offset-2">
                                 {{ Form::text('title',\Illuminate\Support\Facades\Input::get('title'),['class'=>'form-control js-example-basic-single','placeholder'=>'Opinion Title']) }}
                             </div>

                            {{-- <div class="col-md-3 ">
                                 {{ Form::text('email',null,['class'=>'form-control js-example-basic-single','placeholder'=>'Email Address']) }}
                             </div>--}}

                             <div class="col-md-3">
                                 {{ Form::button('<i class="fa fa-search"></i> Search',['type'=>'submit','class'=>'btn btn-primary']) }}
                                 <a href="{{route('opinion_manage.index')}}" class="btn btn-warning"><i
                                             class="fa fa-refresh"></i> Clear</a>
                             </div>

                             {{ Form::close() }}
                         </div>

                     </div>
                     <br>
                     <div class="table-responsive userlistofadmin">
                         @if (count($opinion) > 0)
                             @include('backend.opinion.table_load')
                         @else
                             <h3 style="text-align: center">No Data Found</h3>
                         @endif
                     </div>

                 </div>
             </section>
         </div>
     </div>

@endsection
@push('css')
    <link href="{{ asset('css/table-responsive.css') }}" rel="stylesheet"/>
    <style>
        iframe{width:100% !important;}
    </style>
@endpush
@push('js')
    @include('backend.opinion._script')
@endpush

resources/views/backend/opinion/table_load.blade.php
<table class="display table table-bordered table-striped" id="load">
    <thead>
    <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Image</th>
        <th>Sequence</th>
        <th>Status</th>

        <th class="hidden-phone">Actions</th>
    </tr>


    </thead>
    <tbody>
    @foreach($opinion as $k=>$v)
        <tr class="item{{$v->id}}">
            <td>{{ $serial++ }}</td>
            <td>
                <a class=" btn btn-outline-primary"  href="{{ $v->opinion_details_link }}" target="_blank">
                    <h4>{{ $v->title }}</h4>
                </a>
                <p>{!! $v->short_details !!}</p>
            </td>
            <td>
                <a class=" btn btn-outline-primary"  href="{{ $v->opinion_details_link }}" target="_blank">
                    <img src="{{ $v->image_url }}" height="150px" width="150px">
                </a>
            </td>
            <th> {{ ($v->sequence == null)? 'No':$v->sequence }}</th>
            <th>{{ $v->status }}</th>

            <td>
                <div class="btn-group">
                    <button data-toggle="dropdown" class="btn btn-default dropdown-toggle" type="button"
                            aria-expanded="false">Actions <span class="caret"></span></button>
                    <ul role="menu" class="dropdown-menu float-right">
                        <li>
                            <a href="{{route("opinion_manage.edit",$v->id)}}"><i class="fa fa-edit"></i> Edit</a>
                        </li>
                        <li>
                           {{-- <a href="{{route("opinion_manage.delete",$v->id)}}"><i class="fa fa-trash-o"></i> Delete</a>--}}
                            <a class="delete-modal"  data-id="{{$v->id}}" data-title="{{$v->title}}" href="#"><i class="fa fa-trash-o"></i>Delete</a>

                        </li>
                    </ul>
                </div>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

<ul class="pagination pagination-lg pull-right">{{$opinion->links()}}</ul>


<!-- Modal form to delete a form -->
<div id="deleteModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <h3 class="text-center">Are you sure you want to delete the following post?</h3>
                <br/>
                <form class="form-horizontal" role="form">
                    <div class="form-group" style="display: none">
                        <label class="control-label col-sm-2" for="id">ID:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="id_delete" disabled>
                        </div>
                    </div>
                    <div class="form-group">
                        {{--  <label class="control-label col-sm-2" for="title">Title:</label>--}}
                        <div class="col-sm-10">
                            <h3 id="title" class="text-center text-success"></h3>
                            <input type="hidden" class="form-control" id="title_delete" disabled>
                        </div>
                    </div>
                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger delete" data-dismiss="modal">
                        <span id="" class='fa fa-trash-o'></span> Delete
                    </button>
                    <button type="button" class="btn btn-warning" data-dismiss="modal">
                        <span class='fa fa-times'></span> Close
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>